Доп. опции преобразования
vbondarevsky/Connector pull request #61
Opened 2021-04-03 04:13 UTC by korotovskih

Привет, добавил в параметры преобразования опции которые ранее не использовались:
* Функция преобразования
* Вариант записи даты

2021-04-03 04:45 UTC, korotovskih commented
Есть упавшие тесты на редиректы, т.к. https://httpbin.org сломан, судя по тому что [гуглится](https://github.com/postmanlabs/httpbin/issues/617) уже давно.

2021-05-25 17:32 UTC, artbear commented
в https://github.com/vbondarevsky/Connector/pull/64 более точный код по дополнению работы с json

ИМХО в этом ПР какие-то излишние доработки. с датой вроде бы нет проблем.

2021-05-25 17:36 UTC, korotovskih commented
> в #64 более точный код по дополнению работы с json
> 
> ИМХО в этом ПР какие-то излишние доработки. с датой вроде бы нет проблем.

тест на фичу относится к лишним доработкам?)

2021-06-19 22:23 UTC, vbondarevsky requested changes

2021-06-19 22:23 UTC, vbondarevsky commented on src/CommonModules/КоннекторHTTP/Ext/Module.bsl
> +	НастройкиСериализации.ВариантЗаписиДаты = ПараметрыПреобразованияJSON.ВариантЗаписиДатыJSON;
Нужно добавить ```ВариантЗаписиДатыJSON``` в описание функции

2021-06-19 22:23 UTC, vbondarevsky commented on src/CommonModules/КоннекторHTTP/Ext/Module.bsl
> +			ПараметрыПреобразованияJSON.ИмяФункцииПреобразования,
```ИмяФункцииПреобразования```, ```МодульФункцииПреобразования```, ```ДополнительныеПараметрыФункцииПреобразования``` нужно тоже описать

2021-06-19 22:23 UTC, vbondarevsky commented on src/DataProcessors/Тесты/Ext/ObjectModule.bsl
> +	// Вариант записи даты, функция преобразования
Лучше завести отдельный тест

2021-06-19 22:23 UTC, vbondarevsky commented on src/CommonModules/КоннекторHTTP/Ext/Module.bsl
> +// Предобразует значение типа к типу сериализация которого поддерживается
1. Пре~~Д~~образует
2. запятых не хватает

2021-07-04 01:09 UTC, merged

2021-07-04 03:19 UTC, korotovskih commented
Спасибо большое @vbondarevsky , я все ни как не мог добраться до исправлений =(