#62 Добавить метод КакXML
vbondarevsky/Connector pull request #63
Opened 2021-05-03 13:46 UTC by BlizD

Спасибо за такую полезную библиотеку.

Предлагаю добавить новый метод КакXML, который по ответу возвращает XML с помощью ФабрикаXDTO

2021-05-13 07:39 UTC, BlizD commented
@zeegin @vbondarevsky @kuntashov 
Всем привет.
Подскажите, а владелец репозитория бывает тут?

2021-05-13 09:11 UTC, kuntashov commented
> Подскажите, а владелец репозитория бывает тут?

@BlizD Попробуйте написать Владимиру в телеграме, у него там ник совпадает с ником здесь, на гитхабе.

2021-05-13 09:40 UTC, BlizD commented
@kuntashov Александр, спасибо так и сделаю.

2021-05-29 15:26 UTC, vbondarevsky requested changes
Не хватает теста

2021-05-29 15:26 UTC, vbondarevsky commented on src/CommonModules/КоннекторHTTP/Ext/Module.bsl
> +Функция КакXML(Ответ) Экспорт
Лучше КакXDTO

2021-05-29 15:26 UTC, vbondarevsky commented on src/CommonModules/КоннекторHTTP/Ext/Module.bsl
> +Функция КакXML(Ответ) Экспорт
Также не хватает необязательных параметров:

- ```Кодировка```
- ```Тип``` - ```XDTOValueType | XDTOObjectType```

2021-05-29 15:26 UTC, vbondarevsky commented on src/CommonModules/КоннекторHTTP/Ext/Module.bsl
> +	Перем ОтветXML;
Это лишнее

2021-05-29 15:26 UTC, vbondarevsky commented on src/CommonModules/КоннекторHTTP/Ext/Module.bsl
> +	ЧтениеXML.УстановитьСтроку(ТекстОтвета);
Двойная конвертация получается: сначала двоичные данные в строку, потом строка в XML.
Лучше сразу читать XML из потока

2021-05-31 14:54 UTC, BlizD commented
@vbondarevsky Спасибо, постараюсь на след. выходных посмотреть комментарии.

2021-06-03 04:33 UTC, vbondarevsky commented
Нужен тест:
Можно завязаться на ответ от ЦБ
https://github.com/vbondarevsky/Connector/blob/master/src/DataProcessors/%D0%A2%D0%B5%D1%81%D1%82%D1%8B/Ext/ObjectModule.bsl#L797

Или же сформировать только ответ в нужном виде и проверить метод
https://github.com/vbondarevsky/Connector/blob/master/src/CommonModules/%D0%9A%D0%BE%D0%BD%D0%BD%D0%B5%D0%BA%D1%82%D0%BE%D1%80HTTP/Ext/Module.bsl#L1603-L1612

2021-06-03 12:34 UTC, BlizD commented
Да, тест добавлю на выходных

2021-06-05 05:54 UTC, BlizD commented
@vbondarevsky 
Добрый день, Владимир.
Добавил Тест_ПрочитатьОтветКакXDTO, тест выполняет чтение ответа как XDTO по заготовленному ответу.
Добавил в ReadMe описание метода КакXDTO

2021-06-19 20:39 UTC, vbondarevsky requested changes

2021-06-19 20:39 UTC, vbondarevsky commented on src/CommonModules/КоннекторHTTP/Ext/Module.bsl
> +				Кодировка = Неопределено) Экспорт
Если ```Кодировка``` не заполнена, то ее можно взять из ```Ответ```
как здесь
https://github.com/vbondarevsky/Connector/blob/79596066f78b2fd7d5a005299f6bbf5ef1537146/src/CommonModules/%D0%9A%D0%BE%D0%BD%D0%BD%D0%B5%D0%BA%D1%82%D0%BE%D1%80HTTP/Ext/Module.bsl#L430-L432

2021-06-19 20:39 UTC, vbondarevsky commented on src/CommonModules/КоннекторHTTP/Ext/Module.bsl
> +//		Подробнее см в синтакс помощнике метод ЧтениеXML.ОткрытьПоток
точка после **см** здесь и ниже

2021-06-19 20:39 UTC, vbondarevsky commented on src/CommonModules/КоннекторHTTP/Ext/Module.bsl
> +//   ОбъектXDTO
Нужно добавить какое-то описание для возвращаемого значения

2021-06-19 20:39 UTC, vbondarevsky commented on src/CommonModules/КоннекторHTTP/Ext/Module.bsl
> +//	Кодировка - Строка, КодировкаТекста - Позволяет задать кодировку. Следует указывать для текстов в кодировках
Фраза "Следует указывать для текстов в кодировках" либо лишняя, либо не законченная

2021-06-20 04:51 UTC, BlizD commented
Смогу посмотреть только через неделю.

2021-06-28 12:38 UTC, BlizD commented
@vbondarevsky 
Добрый день, Владимир.
Добавил условие если не заполнена кодировка, то брать из ответа. 
Скорректировал текст комментариев.

2021-06-28 13:04 UTC, merged