Расширены параметры метода ПрочитатьJSON для обработки исключений при…
vbondarevsky/Connector pull request #64
Opened 2021-05-20 09:49 UTC by trumanleks

Расширены параметры метода ПрочитатьJSON для обработки исключений и описании собственной функции восстановления при чтении дат.

2021-05-25 15:43 UTC, artbear requested changes

2021-05-25 15:43 UTC, artbear commented on src/CommonModules/КоннекторHTTP/Ext/Module.bsl
> +		ПараметрыПреобразованияJSON.МаксимальнаяВложенность);
описание метода JsonВОбъект осталось старым.

там всего 3 параметра описано, а новых нет

2021-05-25 17:27 UTC, artbear approved these changes

2021-06-19 22:42 UTC, vbondarevsky requested changes
Не хватает теста

2021-11-14 23:12 UTC, merged